name: Convertible Bond Reminder

on:

  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout actions
      - uses: actions/checkout@v2

      - name: set up python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7

      - name: install
        run: pip install requests

      - name: set reminder message
        run: python main.py ${{secrets.TOKEN}}
