name: Convertible Bond Reminder

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout actions
      - uses: actions/checkout@v2

    - name: set up python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: install
      run: pip install requests

    - name: set reminder message
      run: python main.py ${{secrets.TOKEN}}
